version: '3.2'
volumes:
  app:
  home-dir:

services:
  &app-service app:
    build:
      context: app
      dockerfile: Dockerfile
    hostname: *app-service
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - home-dir:/home/user
    - ./:/var/www
    - ./../../libraries:/var/packages
    command: keep-alive.sh
